### ISSUE TITLE
Some batching options don't seem to work

### ISSUE THREAD

**Issue by syntactic-salt** [splunk/splunk-javascript-logging#71]
Without any batching options set, my log sends immediately as expected. If I set `batchInterval` to `10000`, my  log still sends immediately. This is not expected. What is expected is that my logs would be sent every 10 seconds. If I set `maxBatchSize` to `100000` and send a few characters in the message, my log is sent immediately, so it doesn't appear to respect the size limit. `maxBatchCount` works as expected.

**Comment by midhunm-c** [comment]
The default value for `maxBatchCount` is 1. So try after setting `maxBatchCount = 0` in the configuration, to depend the batch only on the `batchInterval` or `maxBatchSize`. This worked for me.

**Comment by bparmar-splunk** [comment]
Hi @syntactic-salt,
As per @midhunm-c's [comment](https://github.com/splunk/splunk-javascript-logging/issues/71#issuecomment-1216144847), it is correct that by setting **maxBatchCount** to 0, you will be able to configure your values in other two attributes.

Please re-verify your use-case with these changes and let us know incase of any further queries.

Thank you.

**Comment by bparmar-splunk** [comment]
Hi @syntactic-salt,
We did not get any update from you about this issue.
We assume that your issue is resolved based on above [comment](https://github.com/splunk/splunk-javascript-logging/issues/71#issuecomment-1257539484).

We are closing this issue for now.
Please let us know in case of any further queries.

Thank you.
